[material.tumor]
tumorous = false

[model.geometry]
radius_breast = 0.05

[simulation.control_step2]
time_steps = 0

[simulation.output]
output_to_vtk = true
output_to_xplt = true
output_displacement = true
output_stress = false
output_relative_volume = false
