version = 1
disable_existing_loggers = false

[formatters.standard]
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

[formatters.printing]
format = "%(message)s"

[filters.warnings_and_below]
"()" = "ews_fem_pipeline.MaxLevelFilter"
level = "WARNING"

[handlers.stdout]
class = "logging.StreamHandler"
level = "INFO"
formatter = "printing"
stream = "ext://sys.stdout"
filters = [ "warnings_and_below" ]

[handlers.stderr]
class = "logging.StreamHandler"
level = "ERROR"
formatter = "printing"
stream = "ext://sys.stderr"

[handlers.file]
class = "logging.handlers.RotatingFileHandler"
formatter = "standard"
filename = "ews_fem_pipeline.log"
mode = "a"
maxBytes = 1048576
backupCount = 5

[root]
level = "DEBUG"
handlers = [ "stdout", "stderr", "file" ]
