name: CI
on:
  push

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
      - name: Run ruff check
        run: ruff check
